services:
  - type: web
    name: svelte-dmikes
    env: docker
    plan: free
    envVars:
      - key: PORT
        value: 8090
      - key: PB_ENCRYPTION_KEY
    healthCheckPath: /api/health
    disk:
      name: pb_data
      mountPath: /app/pb_data
      sizeGB: 1
